#!/bin/bash

#工作路径设置在脚本的绝对路径下
work_path=$(dirname $0)
cd $work_path

read -p "请输入批量修改的图标icon的名称：" icon_name
#后缀类型为png格式
suffix=".png"
#匹配当前路径下的所有后缀格式为png的图片
png_images=`ls -v *$suffix`
#@2x和@3x的类型变量
twofold="@2x"
threefold="@3x"

#遍历内容
for image in ${png_images[@]}; do
	#默认名称为输入的名称
	img=$icon_name
	#如果遍历的项包含@2x，则拼接
	if [[ $image == *$twofold* ]]; then
		img=$icon_name$twofold
	fi

	#如果遍历的项包含@3x，则拼接
	if [[ $image == *$threefold* ]]; then
		img=$icon_name$threefold
	fi

	#如果图片的名称中不包含.png的后缀，则添加上去
	if [[ $img != *$suffix* ]]; then
		img=$img$suffix
	fi

	#修改文件名称
	mv $image $img
done

echo "compeleted!"
exit 0