#!/bin/bash
#Author by huangsongyao 
#huangsongyao -> https://github.com/huangsongyao

#预先设置好工作脚本时，如果路径中存在空格符或者遍历文件时存在空格符时，预先进行处理
IFS=$(echo -en "\n\b")
#工作路径设置在脚本的绝对路径下【获取脚本名称：script_name=${BASH_SOURCE-$0}】
work_path=$(dirname $0)
cd $work_path

#如果Podfile文件不存在，则写入固定的ruby格式来动态生成这个文件
file="Podfile"
folder="$work_path/$file"
#输入需要pod的目标targets，由于工程可能存在多个target，此处由dev来决定手动输入的targets内容
read -p "请输入需要执行pods的目标targets，如果工程中存在多个target，则请使用英文逗号[,]隔开：" project_target
if [[ ! -f "$folder" ]]; then
#如果不存在，则创建Podfile文件，并使用applescript来写入固定的cocoapods文件的格式内容，其中，默认pod
cat>$file<<EOF
platform :ios, '8.0'
targetsString = '$project_target'
targets = targetsString.split(',')
targets.each do |t|
	target t do
		pod 'RxSwift', '~> 5.0.0'
		pod 'RxCocoa', '~> 5.0.0'
		pod 'ReactiveObjC'
	end
end
EOF
#写入文件后，执行install指令，创建cocoapods插件
vim $file
pod install
#如果install执行失败，则移除当前目录下的Podfile文件并退出
if [[ $? -ne 0 ]]; then	
	rm -rf $file
	rm -rf $file.lock
	pods_files="Pods"
	rm -rf $pods_files
fi

else
#如果已经创建过，则直接执行update指令，更新
vim $file
pod update

fi

#完成后退出进程
echo "completed!"
exit